name: "teast"

on:
  [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read
  # Required for uploading code scanning.
  security-events: write

env:
  JFROG_CLI_LOG_LEVEL: DEBUG

jobs:
  test-binary-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Upload binary
      #   run: |
      #     jf rt u ./binaries/* binary-test/

      # - name: Run scan
      #   run: |
      #     jf scan ./binaries/* --vuln --watches=Security_watch_1 --format=sarif > scan.sarif

      # - name: echo results
      #   run: |
      #     cat scan.sarif

      # - name: publish build info
      #   if : always()
      #   run: |
      #     jf rt build-collect-env
      #     jf rt build-add-git
      #     jf rt build-publish

      # - name: build scan
      #   if : always()
      #   run: |
      #      jf build-scan --vuln --fail=false

      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          # sarif_file: ./scan.sarif
          sarif_file: ./sarif/test.sarif